FROM jenkins/jenkins:lts-jdk17


# Run as root user to allow software installation
USER root


# Install Docker
RUN apt-get update && apt-get install -y docker.io


# continue run Jenkins
CMD ["/usr/local/bin/jenkins.sh"]